version: "3.9"

services:
  frontend:
    image: deepfake-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_VERSION=20-alpine
        - VITE_API_URL=/api
    ports:
      - "8080:8080"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
